name: Commit Automático

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configurar Git
      run: |
        git config --global user.name ' Warren Antonio Villavicencio Merino'
        git config --global user.email 'wavillavicencio@utpl.edu.ec'

    - name: Hacer commit
      run: |
        git add .
        git commit -m "Commit automático"
        git push


